# Константы для моделей
MAX_LENGTH_TAG_NAME = 200
MAX_LENGTH_TAG_SLUG = 200
MAX_LENGTH_INGREDIENT_NAME = 200
MAX_LENGTH_INGREDIENT_UNIT = 50
MAX_LENGTH_RECIPE_NAME = 256
MAX_LENGTH_USER_EMAIL = 254
MAX_LENGTH_USER_FIRST_NAME = 150
MAX_LENGTH_USER_LAST_NAME = 150

MIN_COOKING_TIME = 1
MIN_INGREDIENT_AMOUNT = 1

# Константы для пагинации
PAGE_SIZE = 6
PAGE_SIZE_QUERY_PARAM = 'limit'

# Константы для валидации (если нужны)
MAX_RECIPES_LIMIT = 100
