# Generated by Django 4.2.16 on 2026-08-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
